plans/urls.py
from django.urls import path
from .views import plans, plan_detail, add_plan, toggle_completion

urlpatterns = [
    path('', plans, name='plans'),
    path('add_plan/', add_plan, name='add_plan'),
    path('<int:plan_id>/', plan_detail, name='plan_detail'),
    path('toggle_completion/<int:plan_id>/', toggle_completion, name='toggle_completion'),

]

travel_plans/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from .views import index
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plans/', include('plans.urls')),
    path('', index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])  

plans/models.py
from django.db import models

class TravelPlan(models.Model):
    title = models.CharField(max_length=255, default="Super Plan")
    description = models.TextField(blank=True)
    difficulty = models.IntegerField()
    comfortability = models.IntegerField()
    travel_time = models.IntegerField()
    price = models.CharField(max_length=50)
    activities = models.TextField()
    length = models.IntegerField()
    restrictions = models.TextField()
    plan_type = models.CharField(max_length=50)
    total_score = models.FloatField()
    image = models.ImageField(upload_to='plan_images/', blank=True, null=True)
    completed = models.BooleanField(default=False)


    def __str__(self):
        return self.title

plans/forms.py
from django import forms
from .models import TravelPlan

class TravelPlanForm(forms.ModelForm):
    class Meta:
        model = TravelPlan
        fields = ['title', 'description', 'difficulty', 'comfortability', 'travel_time', 'price', 'activities', 'length', 'restrictions', 'plan_type', 'total_score', 'image']

class TravelPlanCheckForm(forms.ModelForm):
    class Meta:
        model = TravelPlan
        fields = ['completed']

plans/views.py
# plans/views.py

from django.shortcuts import render, get_object_or_404, redirect
from .models import TravelPlan
from .forms import TravelPlanForm, TravelPlanCheckForm
from django.contrib.auth.decorators import login_required


@login_required
def plans(request):
    completed_filter = request.GET.get('completed')
    if completed_filter:
        plans = TravelPlan.objects.filter(completed=False)
    else:
        plans = TravelPlan.objects.all()

    return render(request, 'plans.html', {'plans': plans, 'completed_filter': completed_filter})

@login_required
def plan_detail(request, plan_id):
    plan = get_object_or_404(TravelPlan, pk=plan_id)
    return render(request, "plan_detail.html", {"plan": plan})


@login_required
def add_plan(request):
    if request.method == "POST":
        form = TravelPlanForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("plans")
    else:
        form = TravelPlanForm()

    return render(request, "add_plan.html", {"form": form})


@login_required
def toggle_completion(request, plan_id):
    plan = TravelPlan.objects.get(pk=plan_id)
    if request.method == "POST":
        form = TravelPlanCheckForm(request.POST, instance=plan)
        if form.is_valid():
            form.save()
            return redirect("plan_detail", plan_id=plan_id)
    else:
        form = TravelPlanCheckForm(instance=plan)

    return render(request, "plan_detail.html", {"plan": plan, "form": form})

travel_plans/views.py
from django.shortcuts import render
from datetime import datetime
from dateutil.relativedelta import relativedelta


def calculate_time_passed():
    # Jara's birthdate
    birthdate = datetime(1994, 12, 24)

    # Current date
    current_date = datetime.now()

    age_delta = relativedelta(current_date, birthdate)

    return age_delta
def index(request):
    age_delta = calculate_time_passed()
    context = {
        'age_years': age_delta.years,
        'age_months': age_delta.months,
        'age_days': age_delta.days,
    }

    return render(request, 'index.html', context)

plans/templates/add_plan.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4">
        <h2>Add a New Plan</h2>
        <form method="post" action="{% url 'add_plan' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Add Plan</button>
        </form>
    </div>
{% endblock %}

plans/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Travel Plans{% endblock %}</title>

    <!-- Add your Bootstrap CSS link here -->
    <!-- For example, using CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Jarlands</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'plans' %}">Plans</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'add_plan' %}">Add Plan</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="nav-link btn btn-link">Logout</button>
                    </form>                </li>
                {% else %}
                    <!-- If user is not logged in, show a login link -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


<!-- Page content -->
<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

    <!-- Add your Bootstrap JS and Popper.js scripts here -->
    <!-- For example, using CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-wfSDF2E50iVFBfBWK9O6/QqSsHzu9+6EGftP4nd7u4Rv4JcUzK2E2b3BS9sWh9P0"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyAdq6Qx5c+pc9StJUmatS8oY8e5tJ7Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-bFkT0Bjcu9BS3hAcB+cbf8KXjtjsJ4Lg6w8g5FZtA4W6EaVR0Zl3u2b1IkaP5PZ" crossorigin="anonymous"></script>

    </body>
</html>

plans/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}

<style>
    /* Center the images horizontally and vertically */
    #dynamic-images-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 10vh;
        /* Adjust as needed */
    }

    /* Add spacing between images */
    .img-fluid {
        margin: -1px;
        width: 5%;
        /* Set the width to 50% of the container size */
    }
</style>


<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-4">Jara, congrats!</h1>
        <p class="lead">You've achieved something amazing. You have been born {{age_years}} years, {{age_months}} months
            and {{age_days}} days ago.</p>
        <p>Celebrate your success!</p>
        <p>Push me, and then just touch me till I can get my CE-LE-BRA-TION. CELEBRATION. CELEBRATION.</p>
        <a class="btn btn-primary" href="{% url 'plans' %}">Celebrate!</a>
        <p></p>
        
        <div class="container mt-4">
            <!-- Container for dynamic images -->
            <div id="dynamic-images-container">
                {% for _ in "x"|ljust:10 %}
                <img src="{% static 'congapartyparrot.gif' %}" class="img-fluid" alt="Dynamic GIF">
                {% endfor %}
            </div>
        </div>
        <img src="{% static 'jar_kiss.png' %}" class="card-img-top-fluid" style="max-width: 40%;" alt="Default Image">
    </div>
</div>
{%else%}
<style>
    /* Add spacing between images */
    .img-fluid {
        margin: -1px;
        width: 5%; /* Set the width to 5% of the container size */
    }
</style>

<div class="container mt-4">
    <!-- Container for the first set of images -->
    <div class="text-center">
        {% for _ in "x"|ljust:10 %}
            <img src="{% static 'congapartyparrot.gif' %}" class="img-fluid" alt="Dynamic GIF">
        {% endfor %}
    </div>
    <br>
    <!-- Text section with login button on a new line -->
    <div class="text-center">
        Login please, pretty please.
        <a href="{% url 'login' %}" class="btn btn-success">Login</a>
    </div>
<br>
    <!-- Container for the second set of images on a new line -->
    <div class="text-center">
        {% for _ in "x"|ljust:10 %}
            <img src="{% static 'congapartyparrot.gif' %}" class="img-fluid" alt="Dynamic GIF">
        {% endfor %}
    </div>
</div>

{%endif%}
{% endblock %}

plans/templates/plan_detail.html
<!-- Inside your_app/templates/your_app/plan_detail.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
    <div class="text-center">
        <h1 class="display-4">{{ plan.title }}</h1>
        <p class="lead">Details of the plan:</p>

        <!-- Display the image if available, otherwise use a default image -->
        {% if plan.image %}
        <img src="{{ plan.image.url }}" class="img-fluid" alt="{{ plan.title }}">
        {% else %}
        <img src="{% static 'jarlo.jpeg' %}" class="img-fluid" alt="Default Image">
        {% endif %}

        <!-- Display plan details in a table -->
        <div class="table-responsive mt-3">
            <table class="table table-sm">
                <tbody>
                    <tr>
                        <th scope="row">Completed</th>
                        <td>
                            <form id="completionForm" method="post" action="{% url 'toggle_completion' plan.id %}">
                                {% csrf_token %}
                                <input type="checkbox" id="id_completed" name="completed" {% if plan.completed %}checked{% endif %} onchange="document.getElementById('completionForm').submit()">
                                <label for="id_completed">Completed</label>
                            </form>
                        </td>
                    </tr>

                    <tr>
                        <th scope="row">Description</th>
                        <td>{{ plan.description }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Difficulty</th>
                        <td>{{ plan.difficulty }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Comfortability</th>
                        <td>{{ plan.comfortability }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Travel Time (h)</th>
                        <td>{{ plan.travel_time }} hours</td>
                    </tr>
                    <tr>
                        <th scope="row">Price ($-$$$$$)</th>
                        <td>{{ plan.price }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Activities</th>
                        <td>{{ plan.activities }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Length</th>
                        <td>{{ plan.length }} days</td>
                    </tr>
                    <tr>
                        <th scope="row">Restrictions</th>
                        <td>{{ plan.restrictions }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Type</th>
                        <td>{{ plan.plan_type }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total Score</th>
                        <td>{{ plan.total_score }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

plans/templates/plans.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Card for adding a new plan -->
<div class="row mt-4">
    <div class="col-md-4">
        <div class="card border-primary shadow">
            <div class="card-body">
                <h5 class="card-title">Add a New Plan</h5>
                <p class="card-text">For adding a new plan, click the button below:</p>
                <a href="{% url 'add_plan' %}" class="btn btn-success">Add New Plan</a>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card border-primary shadow">
            <div class="card-body">
                <h5 class="card-title">Filter</h5>
                <form id="completionFilterForm" method="get" action="{% url 'plans' %}">
                    <label for="id_completed">Hide completed plans</label>
                    <input type="checkbox" id="id_completed" name="completed" {% if completed_filter %}checked{% endif %} onchange="document.getElementById('completionFilterForm').submit()">
                </form>
            </div>
        </div>
    </div>

</div>
<style>
    /* Center the images horizontally and vertically */
    #dynamic-images-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 10vh;
        /* Adjust as needed */
    }

    /* Add spacing between images */
    .img-fluid {
        margin: -1px;
        width: 5%;
        /* Set the width to 50% of the container size */
    }
</style>

<div class="container mt-4">
    <!-- Container for dynamic images -->
    <div id="dynamic-images-container">
        {% for _ in "x"|ljust:10 %}
        <img src="{% static 'congapartyparrot.gif' %}" class="img-fluid" alt="Dynamic GIF">
        {% endfor %}
    </div>
</div>

<div class="row">
    {% for plan in plans %}
    <div class="col-md-4 mb-4">
        <div class="card border-primary shadow">
            {% if plan.image %}
            <img src="{{ plan.image.url }}" class="card-img-top-fluid" alt="Plan Image">
            {% else %}
            <!-- Use the default image if no plan image is available -->
            <img src="{% static 'jarlo.jpeg' %}" class="card-img-top-fluid" alt="Default Image">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ plan.title }}</h5>
                <ul class="list-unstyled">
                    <li>Total Score: {{ plan.total_score }}</li>
                </ul>
                <a href="{% url 'plan_detail' plan.id %}" class="btn btn-primary">View Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}